calibrate_ph_probe:
  name: Calibrate pH probe
  description: Send a calibration point to a reef-pi pH probe.
  fields:
    probe_id:
      description: ID of the probe to calibrate
      required: true
      selector:
        number:
          min: 0
          max: 255
          mode: box
    expected:
      description: Expected pH value for the calibration point
      required: true
      selector:
        number:
          min: 0
          max: 14
          step: 0.01
          mode: box
    observed:
      description: Observed pH value for the calibration point
      required: true
      selector:
        number:
          min: 0
          max: 14
          step: 0.01
          mode: box
    type:
      description: Optional calibration type reported by reef-pi
      required: false
      selector:
        text:

calibrate_ph_probe_two_point:
  name: Calibrate pH probe two points
  description: >-
    Perform a two point calibration on a reef-pi pH probe. The probe will be
    calibrated using predefined low and high solutions depending on the chosen
    mode. A countdown is displayed for each step.
  fields:
    probe_id:
      description: ID of the probe to calibrate
      required: true
      selector:
        number:
          min: 0
          max: 255
          mode: box
    mode:
      description: Calibration mode (freshwater or saltwater)
      required: false
      selector:
        select:
          options:
            - "freshwater"
            - "saltwater"

