name: Bump & PR Version

on:
  workflow_dispatch:

jobs:
  bump-and-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install tools
        run: |
          pip install toml
          sudo apt-get update && sudo apt-get install -y jq

      - name: Read and bump version
        id: bump
        run: |
          version=$(python -c "import toml; d=toml.load('pyproject.toml'); v=d['project']['version'].split('.'); v[-1]=str(int(v[-1])+1); print('.'.join(v))")
          echo "new_version=$version" >> $GITHUB_OUTPUT
          python -c "import toml; f='pyproject.toml'; d=toml.load(f); d['project']['version']='$version'; open(f, 'w').write(toml.dumps(d))"
          jq --arg v "$version" '.version=$v' custom_components/reef_pi/manifest.json > custom_components/reef_pi/manifest.json.tmp && mv custom_components/reef_pi/manifest.json.tmp custom_components/reef_pi/manifest.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: release/v${{ steps.bump.outputs.new_version }}
          title: "chore: bump version ${{ steps.bump.outputs.new_version }}"
          commit-message: "chore: bump version ${{ steps.bump.outputs.new_version }}"
          base: master
          body: "Automated PR to bump version to ${{ steps.bump.outputs.new_version }}"
