name: Release

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - "pyproject.toml"
      - "custom_components/reef_pi/manifest.json"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit message
        run: |
          if ! [[ "${{ github.event.head_commit.message }}" =~ ^chore:\ bump\ version ]]; then
            echo "Not a version bump commit; skipping release."
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Tag commit
        id: tag
        run: |
          version=$(python -c "import toml; d=toml.load('pyproject.toml'); print(d['project']['version'])")
          git tag v$version
          git push origin v$version
          echo "::set-output name=new_version::$version"

      - name: Prepare release
        run: |
          bash scripts/prepare_release.sh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.tag.outputs.new_version }}
          prerelease: true
          files: output/reef_pi.zip
