name: Release

on:
  push:
    branches: [master]
    # Only run if commit message bumps version
    paths:
      - 'pyproject.toml'
      - 'custom_components/reef_pi/manifest.json'

jobs:
  release:
    if: startsWith(github.event.head_commit.message, 'chore: bump version')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Tag commit
        id: tag
        run: |
          version=$(python -c "import toml; d=toml.load('pyproject.toml'); print(d['project']['version'])")
          git tag v$version
          git push origin v$version
          echo "::set-output name=new_version::$version"

      - name: Prepare release
        run: |
          bash scripts/prepare_release.sh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.tag.outputs.new_version }}
          prerelease: true
          files: output/reef_pi.zip
